version: "3.7"

services:
  
  app:
    build: app
    restart: always
    networks:
      - frontend-network

  web:
    build: web
    restart: always
    ports:
      - 8080:80
    networks:
      - frontend-network

networks:
  frontend-network: